# This file provides instructions for packaging.

`Scalar-Does`
	perl_version_from m`Scalar::Does`;
	version_from      m`Scalar::Does`;
	readme_from       m`Scalar::Does`;
	requires          p`namespace::clean 0.19`;
	requires          p`IO::Detect 0.001`;
	requires          p`namespace::clean 0.19`;
	requires          p`Scalar::Util 1.23`;
	requires          p`Carp`;
	requires          p`Sub::Exporter`;
	test_requires     p`Test::More 0.61`.

